### ISSUE TITLE
Calling yaml.load() without Loader=... is deprecated

### ISSUE THREAD

**Issue by Nodeswitch** [schwma/gotify-cli-app#2]
Hi - just tested this out today and it's been great so far. Simplified pushing events to Gotify - thanks!

I'm encountering the below when running. It still goes through at the moment, just a heads up!

```
/usr/local/bin/gotify-push:119: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  return yaml.load(yamlString)
```

**Comment by mskian** [comment]
Did you Noticed this Error 

```bash
$ gotify-push -c CONFIG

Traceback (most recent call last):
  File "/usr/bin/gotify-push", line 165, in <module>
    main()
  File "/usr/bin/gotify-push", line 21, in main
    url = parseURLAndConfig(args)
  File "/usr/bin/gotify-push", line 61, in parseURLAndConfig
    config = loadConfig(args.config)
  File "/usr/bin/gotify-push", line 96, in loadConfig
    sys.exit('Could not load config: ' + os.path)
TypeError: must be str, not module
```

**Comment by schwma** [comment]
@mskian It doesn't seem like error you're getting is related to the actual loading of the yaml file, but rather the path that gotify-push is trying to load the config from. Do you have any more details on how you triggered the error?
